#!/bin/sh

#if git rev-parse --verify HEAD >/dev/null 2>&1
if git rev-parse --verify HEAD >/dev/null 2>&1
then
    #echo "pre-commit: About to create a new commit..."
    against=HEAD
else
    echo "pre-commit: About to create the first commit..."
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

if ! C:/repos/FRC-Summer-2024/.venv/Scripts/python.exe -m black src --check --quiet
then
    echo "Must format code correctly"
    exit 1
else
    exit 0
fi